version: "3.9"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bduniversidad
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - datalogger_net

  wildfly:
    image: jeison444/pruebawildfly
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      - postgres
    networks:
      - datalogger_net
    
networks:
  datalogger_net: